# Generated by Django 3.0.3 on 2020-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200313_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='parameters',
            field=models.FileField(upload_to='agent-parameters/%Y/%m/%d/%H%M%S%f'),
        ),
    ]
