# Generated by Django 3.0.3 on 2020-03-15 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_auto_20200315_0127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('name', 'author_id')},
        ),
    ]
