# Generated by Django 3.0.3 on 2020-04-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_computesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computesession',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
