# Generated by Django 3.0.3 on 2020-04-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200415_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='computesession',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='compute_credits',
            field=models.FloatField(default=0),
        ),
    ]
