# Generated by Django 3.0.3 on 2020-03-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='historicalagent',
            old_name='user',
            new_name='author',
        ),
    ]
