# Generated by Django 3.0.3 on 2020-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200306_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='parameters',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='parameters',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
