# Generated by Django 3.0.3 on 2020-03-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200313_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
