# Generated by Django 3.0.3 on 2020-03-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200314_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='web.Agent'),
        ),
    ]
