version: '3'
services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=web

  runner:
    build: ./runner
    command: gunicorn runner.wsgi:application --reload --bind 0.0.0.0:8000
    volumes:
      - ./runner:/usr/src/app/
    env_file:
      - ./runner/.env.dev

  api:
    build: ./api
    command: gunicorn web.wsgi:application --reload --bind 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./api:/usr/src/app/
      - static_data:/usr/src/app/static/
    env_file:
      - ./api/.env.dev
    depends_on:
      - db
      - runner

  nginx:
    build: ./nginx
    volumes:
      - static_data:/usr/share/nginx/static/
    ports:
      - 8080:80
    depends_on:
      - api
      - runner

volumes:
  postgres_data:
  static_data:
