version: '3'
services:
  web:
    build: ./django
    command: python manage.py migrate && gunicorn web.wsgi:application --reload --bind 0.0.0.0:8000
    volumes:
      - ./django:/usr/src/app
    env_file:
      - ./django/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=web

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
