version: '3'
services:
  api:
    build: ./api
    command: python manage.py migrate && gunicorn web.wsgi:application --reload --bind 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./api:/usr/src/app/
      - static_data:/usr/src/app/static/
    env_file:
      - ./api/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=web

  nginx:
    build: ./nginx
    volumes:
      - static_data:/usr/share/nginx/static/
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_data:
